1. VECCTORE Y MATRICES
1.1 SECCION
```{r}
student_1 <- c(50.4,62.3,92.1,77.6,TRUE)
student_2 <- c(41.7,87.9,75.3,72.4,FALSE)
student_3 <- c(30.3,67.8,69.3,71.2,FALSE)
student_4 <- c(65.4,85.1,92.3,96.8,TRUE)
student_5 <- c(70.4,88.2,95.2,90.7,TRUE)
```
1.2. SECCION
```{r}
students_vector <- c(student_1,student_2,student_3,student_4,student_5)
students_vector
```
1.3.SECCION
```{r}
students_matrix <-matrix(students_vector, byrow = TRUE, nrow = 5)
students_matrix
```
2. NOMBRADO DE UNA MATRIZ
2.1.SECCION
```{r}
name_students <-c("Lily Brown","Davis Moore","Susan Taylor","Mike Jones","Tom HIll")
name_cuourse_legal_age <-c("TIC","Accounting","Psychology","Ethics","Legal_age")
```
2.2. seccion
```{r}
colnames(students_matrix) <-name_cuourse_legal_age
rownames(students_matrix) <-name_students
students_matrix
```
3. rowSums,cbind
3.1 seccion
```{r}
total_grade_student <- rowSums(students_matrix[,1:4])
total_grade_student
```
3.2. 
```{r}
result_students <-cbind(students_matrix, total_grade_student)
result_students

```
4 SELECCIONADNDO ELEMENTOS DE UNA MATRIZ
4.1.
```{r}
selected_elements <- result_students [c(1,3,5),c(2,4)]
selected_elements
```
5. DATA FRAMES
5.1 
```{r}
students_grades_df <- data.frame(result_students)
students_grades_df
```
5.2
```{r}
Accounting_mayor_80 <- subset(students_grades_df,Accounting >80)
Seccion_5.2_vectorDATA_FRAME5 <- subset(Accounting_mayor_80,Legal_age > 0)
Seccion_5.2_vectorDATA_FRAME5
```

6. FUNCIONES, CONDICIONALES Y BUCLES
6.1 
```{r}
#students_projection <- function



result_students
result_students[,1:4]


for (li in result_students[,1:4]) {
  if(li <= 45.00){
    print("Student at risk")
  }
  if(li<=61.00){
    print("Studentmay be approved")
  }
  if(li<=100.00){
    print("Student approved")
  }
  
  print(li)
}





```


7. DATA FRAMES Y LAPPLY
7.1
```{r}
index_education <-function(grade){
  return((1+(grade/100))/2 )
  }

index_education(50)

```
7.2
```{r}
all_students_grade <- students_grades_df [,1:4]
```
7.3
```{r}
lapply(all_students_grade,index_education)
```
8 MATH UTILITIES
8.1
```{r}

score_mean <- rowMeans(students_grades_df[,1:4])
score_mean
```


